#
# (c) Copyright 2018 SUSE LLC
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
---

- name: logging-producer | install | Install Beaver from rpm (SUSE)
  become: yes
  package:
    name: python-Beaver
    state: present

- name: logging-producer | install | Configure Beaver to start on boot
  become: yes
  service:
    name: Beaver
    enabled: yes

# add other permissions to allow read access to configuration files
- name: logging-producer | install | Modify Beaver conf directory
  become: yes
  file:
    path: "{{ beaver_conf_dir }}/conf.d"
    state: directory
    mode: o+rx
  register: ardana_notify_beaver_restart

# append group to allow read access to most service logs
- name: logging-producer | install | Modify Beaver user
  become: yes
  user:
    name: "{{ beaver_user }}"
    groups: "{{ beaver_group }}"
    append: yes
  register: ardana_notify_beaver_restart
