#
# (c) Copyright 2016,2017 Hewlett Packard Enterprise Development LP
# (c) Copyright 2017-2018 SUSE LLC
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
---

# Install Kronos API
#------------------------------------------------------------------------------
- name: kronos-api | install | Update venv package cache
  become: yes
  install_package:
    cache: update

- name: kronos-api | install | Install Kronos venv (legacy)
  become: yes
  install_package:
    name: kronos
    service: kronos
    state: present
    activate: act_off
  register: ardana_notify_kronos_api_install
  when: deployer_media_legacy_layout|bool

- name: kronos-api | install | Install Kronos rpm (SUSE)
  become: yes
  package:
    name: openstack-monasca-log-api
    state: present
  register: ardana_notify_kronos_api_install
  when: not deployer_media_legacy_layout|bool

- name: kronos-api | install | Create Kronos API user
  become: yes
  user:
    name: "{{ kronos_user }}"
    group: "{{ kronos_group }}"
    shell: /usr/sbin/nologin
    system: yes
    createhome: no
    home: "{{ kronos_home_dir }}"
  register: ardana_notify_kronos_api_restart

- name: kronos-api | install | Create Kronos API user home
  become: yes
  file:
    path: "{{ kronos_home_dir }}"
    state: directory
    owner: "{{ kronos_user }}"
    group: "{{ kronos_group }}"
    mode: 0700

- name: kronos-api | install | Create Kronos API log directory
  become: yes
  file:
    path: "{{ kronos_log_dir }}"
    state: directory
    owner: "{{ kronos_user }}"
    group: "{{ kronos_group }}"
    mode: 0755
  register: ardana_notify_kronos_api_restart

- name: kronos-api | install | Create a directory to host the log-api WSGI file
  become: yes
  file:
    path: "{{ kronos_wsgi_dir }}"
    state: directory
    owner: "{{ kronos_user }}"
    group: "{{ kronos_group }}"
    mode: 0755
    recurse: yes

- name: kronos-api | install | Link log-api WSGI file
  become: yes
  file:
    src: "{{ 'monasca' | venv_dir }}/bin/monasca-log-api-wsgi"
    dest: "{{ kronos_wsgi_dir }}/monasca-log-api-wsgi"
    state: link
  when: not deployer_media_legacy_layout|bool

