#
# (c) Copyright 2016-2017 Hewlett Packard Enterprise Development LP
# (c) Copyright 2017 SUSE LLC
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
---


# Set logfile groups to adm
#------------------------------------------------------------------------------
- name: logging-server | upgrade | Get list of logfiles to set group to adm
  become: yes
  register: path_files_result
  ignore_errors: yes
  shell: >-
    ls
    /var/log/barbican/barbican.log*
    /var/log/barbican/barbican-worker.log*
    /var/log/barbican/barbican-json.log*
    /var/log/barbican/barbican-worker-json.log*
    /var/log/barbican/barbican-access.log*
    /var/log/barbican/barbican-monitor.log*
    /var/log/kronos/esutil.log*
    /var/log/kronos/logrotate_if_needed.log*
    /var/log/kronos/wsgi.log*
    /var/log/kronos/wsgi-access.log*
    /var/log/ceilometer/ceilometer.log*
    /var/log/ceilometer/ceilometer-api.log*
    /var/log/ceilometer/ceilometer-expirer.log*
    /var/log/ceilometer/ceilometer-polling.log*
    /var/log/ceilometer/ceilometer-collector.log*
    /var/log/ceilometer/ceilometer-preparation.log*
    /var/log/ceilometer/ceilometer-agent-central.log*
    /var/log/ceilometer/ceilometer-agent-compute.log*
    /var/log/ceilometer/ceilometer-alarm-notifier.log*
    /var/log/ceilometer/ceilometer-alarm-evaluator.log*
    /var/log/ceilometer/ceilometer-agent-notification.log*
    /var/log/ceilometer/ceilometer-json.log*
    /var/log/ceilometer/ceilometer-api-json.log*
    /var/log/ceilometer/ceilometer-expirer-json.log*
    /var/log/ceilometer/ceilometer-polling-json.log*
    /var/log/ceilometer/ceilometer-collector-json.log*
    /var/log/ceilometer/ceilometer-preparation-json.log*
    /var/log/ceilometer/ceilometer-agent-central-json.log*
    /var/log/ceilometer/ceilometer-agent-compute-json.log*
    /var/log/ceilometer/ceilometer-alarm-notifier-json.log*
    /var/log/ceilometer/ceilometer-alarm-evaluator-json.log*
    /var/log/ceilometer/ceilometer-agent-notification-json.log*
    /var/log/eon/eon-api.log*
    /var/log/eon/eon-api-json.log*
    /var/log/eon/eon-conductor.log*
    /var/log/eon/eon-conductor-json.log*
    /var/log/freezer-api/freezer-api.log*
    /var/log/ironic/ironic-api.log*
    /var/log/ironic/ironic-api-json.log*
    /var/log/ironic/ironic-conductor.log*
    /var/log/ironic/ironic-conductor-json.log*
    /var/log/ironic/ironic_ipxe_access.log*
    /var/log/ironic/ironic_ipxe_error.log*
    /var/log/monasca/api/monasca-api.log*
    /var/log/monasca/api/request.log*
    /var/log/monasca/notification/notification.log*
    /var/log/monasca/persister/monasca-persister.log*
    /var/log/monasca/agent/collector.log*
    /var/log/monasca/agent/forwarder.log*
    /var/log/monasca/agent/statsd.log*
    /var/log/monasca/agent/supervisord.log*
    /var/log/keystone/keystone.log*
    /var/log/keystone/keystone-json.log*
    /var/log/keystone/keystone_access.log*
    /var/log/keystone/keystone_modwsgi.log*
    /var/log/keystone/keystone_monitoring.log*
    /var/log/keystone/keystone_access.log*
    /var/log/keystone/keystone_modwsgi.log*
    /var/log/keystone/keystone_monitoring.log*
    /var/log/shibboleth/shibd.log*
    /var/log/shibboleth/shibd_warn.log*
    /var/log/shibboleth/signature.log*
    /var/log/shibboleth/transaction.log*
    /var/log/neutron/neutron-ovs-cleanup.log*
    /var/log/neutron/neutron-dhcp-agent.log*
    /var/log/neutron/neutron-dhcp-agent-json.log*
    /var/log/neutron/neutron-l3-agent.log*
    /var/log/neutron/neutron-l3-agent-json.log*
    /var/log/neutron/infoblox-ipam-agent.log*
    /var/log/neutron/infoblox-ipam-agent-json.log*
    /var/log/octavia/octavia-api.log*
    /var/log/octavia/octavia-worker.log*
    /var/log/octavia/octavia-housekeeping.log*
    /var/log/octavia/octavia-health-manager.log*
    /var/log/octavia/octavia-api-json.log*
    /var/log/octavia/octavia-worker-json.log*
    /var/log/octavia/octavia-housekeeping-json.log*
    /var/log/octavia/octavia-health-manager-json.log*
    /var/log/neutron/neutron-l2gateway-agent.log*
    /var/log/neutron/neutron-l2gateway-agent-json.log*
    /var/log/neutron/neutron-lbaas-agent.log*
    /var/log/neutron/neutron-lbaas-agent-json.log*
    /var/log/neutron/neutron-metadata-agent.log*
    /var/log/neutron/neutron-metadata-agent-json.log*
    /var/log/neutron/neutron-openvswitch-agent.log*
    /var/log/neutron/neutron-openvswitch-agent-json.log*
    /var/log/neutron/ovsvapp-agent/monitor.log*
    /var/log/neutron/ovsvapp-agent/monitor-json.log*
    /var/log/neutron/ovsvapp-agent/ovsvapp_agent.log*
    /var/log/neutron/ovsvapp-agent/ovsvapp_agent-json.log*
    /var/log/neutron/neutron-sriov-nic-agent.log*
    /var/log/neutron/neutron-sriov-nic-agent-json.log*
    /var/log/neutron/neutron-server.log*
    /var/log/neutron/neutron-server-json.log*
    /var/log/neutron/neutron-vpn-agent.log*
    /var/log/neutron/neutron-vpn-agent-json.log*
    /var/log/nova/nova-api.log*
    /var/log/nova/nova-api-json.log*
    /var/log/nova/nova-cert.log*
    /var/log/nova/nova-cert-json.log*
    /var/log/nova/nova-conductor.log*
    /var/log/nova/nova-conductor-json.log*
    /var/log/nova/nova-scheduler.log*
    /var/log/nova/nova-scheduler-json.log*
    /var/log/nova/nova-novncproxy.log*
    /var/log/nova/nova-novncproxy-json.log*
    /var/log/nova/nova-baremetal-deploy-helper.log*
    /var/log/nova/nova-baremetal-deploy-helper-json.log*
    /var/log/nova/nova-compute.log*
    /var/log/nova/nova-compute-json.log*
    /var/log/horizon/horizon_access.log*
    /var/log/horizon/horizon_error.log*
    /var/log/horizon/horizon-json.log*
    /var/log/horizon/management/management.log*
    /var/log/horizon/management/management-json.log*
    /var/log/designate/designate-api.log*
    /var/log/designate/designate-mdns.log*
    /var/log/designate/designate-central.log*
    /var/log/designate/designate-pool-manager.log*
    /var/log/designate/designate-zone-manager.log*
    /var/log/designate/designate-api-json.log*
    /var/log/designate/designate-mdns-json.log*
    /var/log/designate/designate-central-json.log*
    /var/log/designate/designate-pool-manager-json.log*
    /var/log/designate/designate-zone-manager-json.log*
    /var/log/ops-console/access.log*
    /var/log/ops-console/error.log*
    /var/log/heat/heat-api.log*
    /var/log/heat/heat-engine.log*
    /var/log/heat/heat-api-json.log*
    /var/log/heat/heat-engine-json.log*
    /var/log/heat/heat-api-cfn-json.log*
    /var/log/heat/heat-api-cloudwatch-json.log*
    /var/log/heat/heat-api-cfn.log*
    /var/log/heat/heat-api-cloudwatch.log*
    2>/dev/null

# NOTE: Those that are commented out are not yet adm in the current version...
# /var/log/configuration_processor/errors.log*
# /var/log/configuration_processor/output.log*
# /var/log/ardana-service/service.log*
# /var/log/logstash/logstash.log*

- name: logging-server | upgrade | Set logfile groups to adm
  become: yes
  file:
    state: file
    path: "{{ item }}"
    group: adm
  ignore_errors: yes
  with_items: path_files_result.stdout_lines

# Delete empty log files
#------------------------------------------------------------------------------
- name: logging-server | upgrade | Get list of empty logfiles to delete
  become: yes
  register: delete_files_result
  ignore_errors: yes
  shell: >-
    find /var/log /var/audit -type f -name "*.log.1" -size 0
    2>/dev/null

- name: logging-server | upgrade | Delete them to avoid blocking logrotation
  become: yes
  file:
    state: absent
    path: "{{ item }}"
  ignore_errors: yes
  with_items: delete_files_result.stdout_lines
